### ISSUE TITLE
Getting toy2.exe Entry Point not found when launching the game with the fix in the installation folder.

### ISSUE THREAD

**Issue by lorenzmartincruz** [RibShark/ToyStory2Fix#10]
Hi! 

Hello there! I have a problem about the fix :(

So i copied the three files (scripts folder, dsound.dll, dsound ini) in the Toy Story 2 installation folder. When I run the game I get this error:

**toy2.exe - Entry Point Not Found**
**The procedure entry point GetThreadId could not be located in the dynamic link library KERNEL32.dll**

The game works great without the fix files, but of course I would like to use the fix for the perfect experience :)

- The only modification i did with the game is that I placed the CD folder in the installation folder and changed regedit. This works like a charm.

I'm using a Lenovo M85e Thinkcentre system with Windows XP 32 bit installed - updated intel and GPU drivers (G210) and all service packs installed. Any thoughts on what things i can try to make it work on my end? Thank you so much!

P.S. I'm really excited about this fix! TS2 was my childhood also so this is awesome! Thank you for taking the time to do this!

**Comment by RibShark** [comment]
Windows XP is not supported, unfortunately. It is too much work to support obsolete operating systems. The game should work pretty well on XP without the fix.
