### ISSUE TITLE
Little graphical glitches and starrting problem

### ISSUE THREAD

**Issue by spiken0** [RibShark/ToyStory2Fix#5]
Hey, great work with this fix. I do have  these following issues. When i start the game the launcher works fine but after that the game works just in a small window of 1/4 size of the desktop(it is not windowed cos i can't resize or fullscreen that window it just shows 1/4 of the game image on 1/4 of desktop) it's not a big deal cos everything works fine if dgvoodoo2 is used. Second issue is some small graphical glitches in the game, wierd flickering textures on the book shelve in the starting room and on the robot "first boss"(didn't get any further so i don't know how it looks further on) it's possible to fix those flickering textures if in dgvoodoo2 anisotropic filtering is enabled but that introduces another issue(weird squares on the walls) None of these issues are game braking buggs and the game is playable so not a big deal but i thought that i'd report them anyway.

**Comment by gamerfreak147** [comment]
Had the same problem with the window size. Try adjusting the program's DPI scaling it worked for me. 
 I'm using Windows 10. Side note the highest resolution I can run at is 2048 x 1536 x 32. 
Any higher resolution crashes for me.
![image](https://user-images.githubusercontent.com/30555846/51431841-55628180-1bf4-11e9-8032-96c0505d3963.png)

**Comment by TyrannoWright** [comment]
Doesn't seem to work for me. I have to use 1920x1080x16 to get it to run. Otherwise x32 just goes to 1/4 size on my screen.

Edit: Resolutions lower than my native (1920x1080) seem to work in x32, but higher than native crashes the game.

**Comment by gamerfreak147** [comment]
Interesting, my monitor is 4K. So our monitors work fine in x32 if the resolution is set lower than our native resolutions on our monitors.

**Comment by TyrannoWright** [comment]
Solved my issue. I went into my AMD Radeon Settings and disabled GPU Scaling along with Virtual Super Resolution. I don't have a clue in the world why it would cause the issue, but there it is.
