### ISSUE TITLE
Widescreen support broken?

### ISSUE THREAD

**Issue by ghost** [RibShark/ToyStory2Fix#6]
Can't seem to get this to work, any tips?

**Comment by RibShark** [comment]
Which region of the game are you using? Can you provide any screenshots?

**Comment by ghost** [comment]
Hi sorry I forgot about this.

My resolution is 3440x1440 ultrawide. Ideally I wanted to get it working with this.

It will load up with the ingame 1920x1440 but nothing higher (or it will crash). In game however, it is 4:3 still.

I believe I have the german version. Thanks for your help @RibShark

**Comment by RibShark** [comment]
Ah, resolutions wider than 2048 pixels will crash on native ddraw, therefore this is a likely duplicate of of #3. Feel free to reopen the issue if you think there's something else going on.

**Comment by ghost** [comment]
Shouldn't widescreen support be working at 1920x1440 though because it's not for me? I only ever get 4:3.

**Comment by ghost** [comment]
@RibShark tagging so you see this, don't think I can reopen.
